//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManager.config", typeof(config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ContinuousLabel Version=&quot;8.0&quot; Units=&quot;twips&quot;&gt;
        ///	&lt;PaperOrientation&gt;Landscape&lt;/PaperOrientation&gt;
        ///	&lt;Id&gt;Tape12mm&lt;/Id&gt;
        ///	&lt;PaperName&gt;12mm&lt;/PaperName&gt;
        ///	&lt;LengthMode&gt;Auto&lt;/LengthMode&gt;
        ///	&lt;LabelLength&gt;0&lt;/LabelLength&gt;
        ///	&lt;RootCell&gt;
        ///		&lt;TextObject&gt;
        ///			&lt;Name&gt;TEXT&lt;/Name&gt;
        ///			&lt;ForeColor Alpha=&quot;255&quot; Red=&quot;0&quot; Green=&quot;0&quot; Blue=&quot;0&quot; /&gt;
        ///			&lt;BackColor Alpha=&quot;0&quot; Red=&quot;255&quot; Green=&quot;255&quot; Blue=&quot;255&quot; /&gt;
        ///			&lt;LinkedObjectName /&gt;
        ///			&lt;Rotation&gt;Rotation0&lt;/Rotation&gt;
        ///			&lt;IsMirrored&gt;False&lt;/IsMirrored&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string label_config {
            get {
                return ResourceManager.GetString("label_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ContinuousLabel Version=&quot;8.0&quot; Units=&quot;twips&quot;&gt;
        ///	&lt;PaperOrientation&gt;Landscape&lt;/PaperOrientation&gt;
        ///	&lt;Id&gt;Tape12mm&lt;/Id&gt;
        ///	&lt;PaperName&gt;12mm&lt;/PaperName&gt;
        ///	&lt;LengthMode&gt;Auto&lt;/LengthMode&gt;
        ///	&lt;LabelLength&gt;0&lt;/LabelLength&gt;
        ///	&lt;RootCell&gt;
        ///		&lt;TextObject&gt;
        ///			&lt;Name&gt;TEXT&lt;/Name&gt;
        ///			&lt;ForeColor Alpha=&quot;255&quot; Red=&quot;0&quot; Green=&quot;0&quot; Blue=&quot;0&quot; /&gt;
        ///			&lt;BackColor Alpha=&quot;0&quot; Red=&quot;255&quot; Green=&quot;255&quot; Blue=&quot;255&quot; /&gt;
        ///			&lt;LinkedObjectName /&gt;
        ///			&lt;Rotation&gt;Rotation0&lt;/Rotation&gt;
        ///			&lt;IsMirrored&gt;False&lt;/IsMirrored&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string label_config_small {
            get {
                return ResourceManager.GetString("label_config_small", resourceCulture);
            }
        }
    }
}
